name: refresh stations

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
        - "**"
  schedule:
    - cron: '15 3 */14 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}



  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Run Python app
        run: docker run ghcr.io/gabrieleghisleni/gasolineprices:opengasoline-v2 poetry run python src/static_stations.py

      - name: Run refresh details script
        run: docker run ghcr.io/gabrieleghisleni/gasolineprices:opengasoline-v2 poetry run python src/refresh_details.py

  test:
    needs: [build, deploy]
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        continue-on-error: true
        run: docker run ghcr.io/gabrieleghisleni/gasolineprices:opengasoline-v2 poetry run pytest src/test_static_stations.py

  post-deploy:
      runs-on: ubuntu-latest
      needs: [build, test]

      steps:
        - name: Commit and push changes
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Update data"
            git push

