name: refresh stations
DOCKER_IMAGE_NAME: ghcr.io/GabrieleGhisleni/GasolinePrices/opengasoline:latest

on:
  push:
    branches:
        - "**"
  schedule:
    - cron: '15 3 */14 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ DOCKER_IMAGE_NAME }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Run Python app
        run: docker run ${{ DOCKER_IMAGE_NAME }} poetry run python src/static_stations.py

      - name: Run refresh details script
        run: docker run ${{ DOCKER_IMAGE_NAME }} poetry run python src/refresh_details.py

  test:
    needs: [build, deploy]
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        continue-on-error: true
        run: docker run ${{ DOCKER_IMAGE_NAME }} poetry run pytest src/test_static_stations.py

  post-deploy:
      runs-on: ubuntu-latest
      needs: [build, test]

      steps:
        - name: Commit and push changes
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Update data"
            git push

