name: refresh stations

on:
  push:
    branches:
        - "**"
  schedule:
    - cron: '15 3 */14 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.4'

      - name: install Poetry
        uses: snok/install-poetry@v1

      - name: install dependencies
        run: poetry install --no-interaction

  fetch:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./"
    steps:
      - name: execute py script
        run: poetry run python src/static_stations.py

  tests:
    needs: fetch
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./"
    steps:
      - name: execute tests
        run: poetry run pytest tests/test_static_stations.py

  updatingGit:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "update data" -a

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master


