name: refresh stations

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: gabrieleghisleni
  DOCKER_REPOSITORY: gasolineprices
  DOCKER_IMAGE: ghcr.io/gabrieleghisleni/gasolineprices:opengasoline-v2

on:
  push:
    branches:
        - "*"
  schedule:
    - cron: '15 3 */14 * *'

jobs:
  login-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: login-registry
    steps:
      - name: Refresh static stations
        run: docker run ${{ env.DOCKER_IMAGE }} poetry run python static_stations.py

      - name: Run refresh details script
        run: docker run  ${{ env.DOCKER_IMAGE }} poetry run python refresh_details.py

  test:
    needs:  deploy
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        continue-on-error: true
        run: docker run ${{ env.DOCKER_IMAGE }} poetry run pytest test_static_stations.py

  post-deploy:
      runs-on: ubuntu-latest
      needs:  test

      steps:
        - name: Commit and push changes
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Update data"
            git push

