name: refresh stations

on:
  push:
    branches:
        - "**"
  schedule:
    - cron: '15 3 */14 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/GabrieleGhisleni/GasolinePrices/opengasoline:latest
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Run Python app
        run: docker run ghcr.io/GabrieleGhisleni/GasolinePrices/opengasoline:latest poetry run python src/static_stations.py

      - name: Run refresh details script
        run: docker run ghcr.io/GabrieleGhisleni/GasolinePrices/opengasoline:latest poetry run python src/refresh_details.py

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        continue-on-error: true
        run: docker run ghcr.io/GabrieleGhisleni/GasolinePrices/opengasoline:latest poetry run pytest src/test_static_stations.py

  post-deploy:
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update data"
        git push

