name: refresh stations

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: gabrieleghisleni
  DOCKER_REPOSITORY: open-gasoline
  DOCKER_IMAGE: ghcr.io/gabrieleghisleni/open-gasoline

on:
  push:
    branches:
        - "**"
  schedule:
    - cron: '15 3 */14 * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Refresh static stations
        run: docker run ${{ env.DOCKER_IMAGE }} poetry run python static_stations.py

      - name: Run refresh details script
        run: docker run  ${{ env.DOCKER_IMAGE }} poetry run python refresh_details.py

  test:
    needs:  deploy
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        continue-on-error: true
        run: docker run ${{ env.DOCKER_IMAGE }} poetry run pytest test_static_stations.py

  post-deploy:
      runs-on: ubuntu-latest
      needs:  test

      steps:
        - name: Commit and push changes
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Update data"
            git push

