name: scraper-gasoline-italian-prices

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: gabrieleghisleni
  DOCKER_REPOSITORY: open-gasoline
  DOCKER_IMAGE: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}

on:
  push:
    branches:
      - "**"
  schedule:
    - cron: '15 1 */2 * *'

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
      - name: Run refresh details script
        run: docker run ${{env.DOCKER_IMAGE}} poetry run python fetch_and_save.py

  test:
    needs: [build, deploy]
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        continue-on-error: true
        run: docker run  ${{env.DOCKER_IMAGE}} poetry run pytest test_refresh_prices.py

  post-deploy:
      runs-on: ubuntu-latest
      needs: [build, test]

      steps:
        - name: Commit and push changes
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Update data"
            git push


